{% set name = "torsiondrive" %}
{% set version = "1.2.0" %}
{% set sha256 = "5070caca20b08ddada56623b15bc03c7e70a05cdfeec7273f10a84e877840fef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - torsiondrive-launch = torsiondrive.launch:main
    - torsiondrive-api = torsiondrive.td_api:main
    - torsiondrive-plot1d = torsiondrive.tools.plot_1d:main
    - torsiondrive-plot2d = torsiondrive.tools.plot_2d:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - {{ pin_compatible('numpy', lower_bound='1.11', upper_bound='3.0') }}
    - geometric >=0.9.7
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pytest
    - matplotlib
      # for more extensive testing
    - psi4
    - ndcctools
  imports:
    - torsiondrive
      # commands:
      # many tests need repo files that aren't included in pkg
      # These tests currently fail because The file hooh.xyz can not be found. 
      # An update to torsiondrive may be needed to point to the correct location:
      # https://github.com/conda-forge/torsiondrive-feedstock/pull/10/files#diff-a11353f33173c7513587242726d6f03bbac8102fe7e32f2e203a1d178f7ec139
      # - pytest -rws -v --durations=20 --color yes $SP_DIR/torsiondrive -k "not _gaussian_ and not _stack_ and not _reproduce_ and not work_queue"


about:
  home: https://github.com/lpwgroup/torsiondrive
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dihedral scanner with wavefront propagation
  dev_url: https://github.com/lpwgroup/torsiondrive

extra:
  recipe-maintainers:
    - leeping
    - dgasmith
    - yudongqiu
    - j-wags
    - loriab
    - bennybp
