{% set name = "torsiondrive" %}
{% set version = "0.9.7" %}
{% set sha256 = "12e7370b718933fdb9389295f027fbb683ba49a106e2afc652f4e26c247d0230" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - torsiondrive-launch = torsiondrive.launch:main
    - torsiondrive-api = torsiondrive.td_api:main

requirements:
  host:
    - python >=3
    - setuptools
    - pip
  run:
    - {{ pin_compatible('numpy', lower_bound='1.11') }}
    - geometric
    - python >=3

test:
  imports:
    - torsiondrive

about:
  home: https://github.com/lpwgroup/torsiondrive
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dihedral scanner with wavefront propagation'
  dev_url: https://github.com/lpwgroup/torsiondrive

extra:
  recipe-maintainers:
    - leeping
    - dgasmith
    - yudongqiu
