{% set name = "torsiondrive" %}
{% set version = "1.1.0" %}
{% set sha256 = "5e8c064b875c301dc546d3adac479af17d649e2ac7bdb753fd6ff8a1521d5294" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-py312-and-np-v2-compat.patch

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - torsiondrive-launch = torsiondrive.launch:main
    - torsiondrive-api = torsiondrive.td_api:main
    - torsiondrive-plot1d = torsiondrive.tools.plot_1d:main
    - torsiondrive-plot2d = torsiondrive.tools.plot_2d:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - {{ pin_compatible('numpy', lower_bound='1.11', upper_bound='3.0') }}
    - geometric >=0.9.7
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pytest
    - matplotlib
    - psi4
    - ndcctools
  imports:
    - torsiondrive
  commands:
      # many tests need repo files that aren't included in pkg
    - pytest -rws -v --durations=20 --color yes -n auto $SP_DIR/torsiondrive -k "not _gaussian_ and not _stack_ and not _reproduce_"

about:
  home: https://github.com/lpwgroup/torsiondrive
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dihedral scanner with wavefront propagation
  dev_url: https://github.com/lpwgroup/torsiondrive

extra:
  recipe-maintainers:
    - leeping
    - dgasmith
    - yudongqiu
