travis:
  secure:
    BINSTAR_TOKEN: IdG813NsAWgNubthtiRAVfXu+dg9FcvhNDVGGmdbxlQcJbVxbvfLPYvmh7282dHlFWJ98/lUrmS/5+Nfi36aD7wvWZA7pgoZsqk2C+VcDZJQfaeBj6jSFHZe5qMCZcoHAZyULdoBo/sUD2fJnsw5Lelii4Z0dfPjSYnbHGARKingvUsAtMkWzK4dqwkWRuSMoHy6cBuxq/OteYCvERQbETzk7e/7/JhkdDKrozproPhnOQ0L+8KQ0LcW7fz5Lf7r+xa7OzdKH/yX4WhTCnhMdj9aikyT9T4NuqTO2iO/opEPxDjhilwMETyeeaC3T9WuhVRC6cfCVon4il1yws06qNY8IyR0ZZQOaBASEJvGi5UczchegZwJv194N40ESlrC6RsoONb6h72+phwLbKSTVFlWD4hdi5d7zYz67BBBkc+H75Ixq/YEC87tLF2Beydn+LRD4HcQBfZ8lE87RFcwmPS/TSgEcGlBj2fu1wqel3la0cMtyp5p63HNisajjAFwpBCoj5SGbZQlXjYkq3NVqRPdPWwf774zj5vVoVUdJwxKWkA1ikhsis/fYjfIxiTGjyDaUx1A8bpvt9UFBHAKa67LdzcmoJki6ax5kQY04LbAt8u9CgvuOr/9RdIs/YeZCxwlheCP0Mv+CnsN28gItS2F5HxPQHjpW2xIcfc5NAA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
